# Generated by Django 3.0.5 on 2020-12-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
                ('fund_ratio2020', models.FloatField(max_length=4)),
                ('fund_ratio2019', models.FloatField(max_length=4)),
                ('fund_ratio2018', models.FloatField(max_length=4)),
                ('fund_ratio2017', models.FloatField(max_length=4)),
                ('fund_ratio2016', models.FloatField(max_length=4)),
                ('fund_ratio_avg', models.FloatField(max_length=4)),
                ('fund_rate1', models.FloatField(max_length=4)),
                ('fund_rate2', models.FloatField(max_length=4)),
                ('fund_rate3', models.FloatField(max_length=4)),
                ('fund_rate4', models.FloatField(max_length=4)),
                ('fund_rate_sum', models.FloatField(max_length=4)),
                ('fund_position_shares', models.FloatField(max_length=4)),
                ('fund_position_bond', models.FloatField(max_length=4)),
                ('fund_position_other', models.FloatField(max_length=4)),
            ],
        ),
    ]
